name: entao_message
description: Dispatch message with variant arguments.
version: 1.0.0
repository: https://github.com/yangentao/entao_message
homepage: https://github.com/yangentao/entao_message

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  entao_lint: ^1.0.1
#  entao_dutil: ^2.1.1
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
